### ISSUE TITLE
Encourage sleep for those who are still awake

### ISSUE THREAD

**Issue by niuez** [niuez/nakochan#13]
1時に寝るさん...

- 名前を読む？
- ロールを読む？

**Comment by m1zz1y** [comment]
「 `${名前}` さん、そろそろ `${時間}` 時です。寝る準備をしましょうね」（10, 15 分前）
「 `${名前}` さん、`${時間}` 時に寝るって言ってましたよね？」（時間ちょうど）
「 `${名前}` さん、おやすみなさい！」（5 分オーバーで kick とか）
とか

**Comment by niuez** [comment]
https://discordpy.readthedocs.io/ja/latest/api.html?highlight=member#discord.Member.move_to
vcからのkick
